language: objective-c
osx_image: xcode10.1
node_js: 10
before_install:
- openssl aes-256-cbc -K $encrypted_a43c9d4ca4d4_key -iv $encrypted_a43c9d4ca4d4_iv
  -in dist.p12.enc -out scripts/travis/dist.p12 -d
- security create-keychain -p mysecretpassword build.keychain
- security default-keychain -s build.keychain
- security unlock-keychain -p mysecretpassword build.keychain
- security set-keychain-settings -t 3600 -u build.keychain
- security import ./scripts/travis/dist.p12 -k build.keychain -T /usr/bin/codesign
  -P ""
- 'security set-key-partition-list -S apple-tool:,apple: -s -k mysecretpassword build.keychain'
install:
- wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
- tar -zxvf GeoLite2-Country.tar.gz
- mv GeoLite2-Country_*/GeoLite2-Country.mmdb ./ClashX/Support\ Files/Country.mmdb
- cd ClashX/Resources
- git clone -b gh-pages https://github.com/Dreamacro/clash-dashboard.git dashboard
- cd ..
- go version
- go build -buildmode=c-archive
- cd $TRAVIS_BUILD_DIR
script:
- 'xcodebuild -workspace ClashX.xcworkspace -scheme "ClashX" build CODE_SIGN_IDENTITY="Developer
  ID Application: Fuzhou West2Online Internet Inc. (MEWHFZ92DY)"| xcpretty'

before_deploy:
- gem install gym
- fastlane gym -s ClashX
- npm install --global create-dmg
- create-dmg ClashX.app
- mv ClashX*.dmg ClashX.dmg

deploy:
  provider: releases
  prerelease: false
  skip_cleanup: true
  api_key:
    secure: YKO96FhN1JgvM+EiyciNQCu8nk/t87txxCEA5//XuKGKh+75tVyB+udmEL4sQL2R01vuShO5WwXLRulHkDsVFjNgvTGa64cdG6SMNORMI+mEuBW2L/RPtkaK1GAY+l+iGkH9i1Ng0SaDqL8xSc5rkqicdUV9NSDrg3k+Ck0pu/DvHgwHAmIjN0JG73TuQKfENDlwoa/uj6ztXpxGR30vgobqaex8wwGV+9fs8Jfbh3cO/79iGXweRhJptvvW0EAF1vV95KyEaUYtHP+7NYVVapOCWwek2irdn1HBm4pRib/0bHh/wFQgnI9OoQbKYuKNc6xRnt9h0wWh+SSIwRA1X7jiZTipli+7G2HGXpvW0r8jMskhYxqjcRH5EWB8rGXoiy/16GUuY1SK1ID/oW9nSh5ws6quaRBmpXGyJcoOUq9STsF+HVOF1DOX4qRt8B7049ytdKIRNe3QGmOlc8w3Nyi5y/v9CHWmVWRrKvzJ8qXP/+JJlFIsXhZR+TYqosiX2ZoKpanLv1RFFbU5FxqdaQapQX465FlpoD/6Qhv+2WLmLBgI1+ewR6g/wjLus6unVu4C3ztYov/9Y7OhYlfD+CqdzKOn+98gGAPRV92MfFh8Qa6rXjsVbP4dC09zKze/+OZtCXr36C5M40MYIChVuSUlDSG4IhElylboSYvQ/wQ=
  file: 
    - ClashX.dmg
    - ClashX.app.dSYM.zip

  on:
    repo: yichengchen/clashX
    branch: master
    tags: true
